// @ts-nocheck
"use client";

import { useEffect, useState } from "react";

const money = (value) => Number(value || 0).toLocaleString() + " ETB";

export default function DashboardClient() {
  const [data, setData] = useState({ income: [], expenses: [], totals: { income: 0, expenses: 0, profit: 0 } });
  const [filter, setFilter] = useState("all");
  const [form, setForm] = useState({ category: "Maintenance", description: "", amount: "", payment_method: "cash" });
  const load = async () => { const response = await fetch("/api/hono/finance"); if (response.ok) setData(await response.json()); };
  useEffect(() => { load(); }, []);
  const addExpense = async (event) => { event.preventDefault(); const response = await fetch("/api/hono/expenses", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); if (response.ok) { setForm({ ...form, description: "", amount: "" }); load(); } };
  const rows = [...(filter === "expenses" ? [] : data.income.map((item) => ({ ...item, kind: "Income", date: item.transaction_date }))), ...(filter === "income" ? [] : data.expenses.map((item) => ({ ...item, kind: "Expense", date: item.expense_date })))].sort((a, b) => String(b.date).localeCompare(String(a.date)));
  return <section className="financePage"><div className="operationsHeader"><div><p className="eyebrow">Owner control</p><h1>Finance dashboard</h1><p>Track paid orders, manual spending, and the live restaurant profit.</p></div><button className="button buttonLine" onClick={load}>Refresh</button></div><div className="financeCards"><div className="panel"><span>Income</span><strong>{money(data.totals.income)}</strong></div><div className="panel"><span>Expenses</span><strong>{money(data.totals.expenses)}</strong></div><div className="panel profitCard"><span>Net profit</span><strong>{money(data.totals.profit)}</strong></div></div><div className="financeGrid"><form className="panel expenseForm" onSubmit={addExpense}><p className="eyebrow">Manual expense</p><h2>Add spending</h2><label>Category<select value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })}>{["Ingredients", "Maintenance", "Salaries", "Rent", "Utilities", "Transport", "Marketing", "Other"].map((item) => <option key={item}>{item}</option>)}</select></label><label>Description<input required value={form.description} placeholder="TV maintenance" onChange={(e) => setForm({ ...form, description: e.target.value })} /></label><label>Amount (ETB)<input required min="1" type="number" value={form.amount} placeholder="500" onChange={(e) => setForm({ ...form, amount: e.target.value })} /></label><label>Payment method<select value={form.payment_method} onChange={(e) => setForm({ ...form, payment_method: e.target.value })}><option value="cash">Cash</option><option value="card">Card</option><option value="telebirr">Telebirr</option><option value="other">Other</option></select></label><button className="button buttonGold fullButton">Save expense</button></form><div className="panel financeList"><div className="adminPanelHead"><div><p className="eyebrow">Transactions</p><h2>Income and expenses</h2></div><select value={filter} onChange={(e) => setFilter(e.target.value)}><option value="all">All transactions</option><option value="income">Income only</option><option value="expenses">Expenses only</option></select></div>{rows.length ? rows.map((row) => <div className="transactionRow" key={row.id}><div><strong>{row.description}</strong><span>{row.category} · {row.date}</span></div><b className={row.kind === "Expense" ? "expenseAmount" : "incomeAmount"}>{row.kind === "Expense" ? "-" : "+"}{money(row.amount)}</b></div>) : <p className="mutedText">No transactions yet. Paid waiter orders and owner expenses will appear here.</p>}</div></div></section>;
}

